<div class="table-scrollable">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    Merchant Kategori Adı
                </th>
                <th>
                    Atanmayan Ürün Sayısı
                </th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody data-bind="foreach: items ">
            <tr>
                <td data-bind="text: title"><small></small></td>
                <td data-bind="text: count"></td>
                <td><a href="#catFrame"  data-bind="click: $parent.loadSignData" role="button" data-toggle="modal" class="btn default btn-mini blue"><i class="fa fa-share"></i>Kategori Ata</a></td>
            </tr>
    </table>
    <div data-bind="visible: loading" style="padding: 50px; text-align: center;">
        <img src="/themes/metronic/assets/global/img/loading-spinner-blue.gif" />
    </div>
</div>




<div id="catFrame" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Kategori Atama</h4>
            </div>
            <div class="modal-body">
                
                <form action="#" class="form-horizontal">
                    <div class="form-body">
                        
                        <div class="form-group">
                            <label class="col-md-3 control-label">From</label>
                            <div class="col-md-6">
                                <div class="input-icon right">
                                    <i class="fa "></i>
                                    <input type="text" class="form-control" value="Etek" disabled="disabled">
                                </div>
                            </div>
                        </div>
                        
                        
                        <div class="form-group">
                            <label class="col-md-3 control-label">To</label>
                            <div class="col-md-6">
                                <div class="input-icon right">
                                    <i class="fa "></i>
                                    <input type="text" class="form-control">
                                </div>
                            </div>
                        </div>
                        
                        
                        <p>
                            <h4 class="modal-title">Seçimi Kesinleştir</h4>
                        </p>
                        
                        
                        <div class="form-group">
                            <label class="col-md-3 control-label">Affiliate Offers</label>
                            <div class="col-md-6">
                                <div class="input-group">
                                    <span class="input-group-addon">
                                    <i class="fa fa-envelope"></i>
                                    </span>
                                    <select class="form-control">
                                        <option>[Seçiniz..]</option>
                                        <?php foreach($affiliateOffers as $id=>$aff) echo "<option value='$id'>$aff[name]</option>" ?>
                                    </select>
                                </div>
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-md-3 control-label">Cinsiyet</label>
                            <div class="col-md-6">
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <i class="fa fa-user"></i>
                                    </span>
                                    <select class="form-control">
                                        <option value="">[Seçiniz..]</option>
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                    </select>
                                    
                                </div>
                            </div>
                        </div>

                        <div class="portlet box green">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-envelope"></i>Örnek resimler
							</div>
						</div>
						<div class="portlet-body">
                            <div class="row">
                                
                                
								<div class="col-sm-6 col-md-3">
									<a href="#" class="thumbnail">
									<img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxNjIiIGhlaWdodD0iMTgwIj48cmVjdCB3aWR0aD0iMTYyIiBoZWlnaHQ9IjE4MCIgZmlsbD0iI2VlZSIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjgxIiB5PSI5MCIgc3R5bGU9ImZpbGw6I2FhYTtmb250LXdlaWdodDpib2xkO2ZvbnQtc2l6ZToxMnB4O2ZvbnQtZmFtaWx5OkFyaWFsLEhlbHZldGljYSxzYW5zLXNlcmlmO2RvbWluYW50LWJhc2VsaW5lOmNlbnRyYWwiPjE2MngxODA8L3RleHQ+PC9zdmc+" alt="100%x180" style="height: 180px; width: 100%; display: block;" data-src="holder.js/100%x180">
									</a>
								</div>
								<div class="col-sm-6 col-md-3">
									<a href="#" class="thumbnail">
									<img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxNjIiIGhlaWdodD0iMTgwIj48cmVjdCB3aWR0aD0iMTYyIiBoZWlnaHQ9IjE4MCIgZmlsbD0iI2VlZSIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjgxIiB5PSI5MCIgc3R5bGU9ImZpbGw6I2FhYTtmb250LXdlaWdodDpib2xkO2ZvbnQtc2l6ZToxMnB4O2ZvbnQtZmFtaWx5OkFyaWFsLEhlbHZldGljYSxzYW5zLXNlcmlmO2RvbWluYW50LWJhc2VsaW5lOmNlbnRyYWwiPjE2MngxODA8L3RleHQ+PC9zdmc+" alt="100%x180" style="height: 180px; width: 100%; display: block;" data-src="holder.js/100%x180">
									</a>
								</div>
								<div class="col-sm-6 col-md-3">
									<a href="#" class="thumbnail">
									<img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxNjIiIGhlaWdodD0iMTgwIj48cmVjdCB3aWR0aD0iMTYyIiBoZWlnaHQ9IjE4MCIgZmlsbD0iI2VlZSIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjgxIiB5PSI5MCIgc3R5bGU9ImZpbGw6I2FhYTtmb250LXdlaWdodDpib2xkO2ZvbnQtc2l6ZToxMnB4O2ZvbnQtZmFtaWx5OkFyaWFsLEhlbHZldGljYSxzYW5zLXNlcmlmO2RvbWluYW50LWJhc2VsaW5lOmNlbnRyYWwiPjE2MngxODA8L3RleHQ+PC9zdmc+" alt="100%x180" style="height: 180px; width: 100%; display: block;" data-src="holder.js/100%x180">
									</a>
								</div>
								<div class="col-sm-6 col-md-3">
									<a href="#" class="thumbnail">
									<img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxNjIiIGhlaWdodD0iMTgwIj48cmVjdCB3aWR0aD0iMTYyIiBoZWlnaHQ9IjE4MCIgZmlsbD0iI2VlZSIvPjx0ZXh0IHRleHQtYW5jaG9yPSJtaWRkbGUiIHg9IjgxIiB5PSI5MCIgc3R5bGU9ImZpbGw6I2FhYTtmb250LXdlaWdodDpib2xkO2ZvbnQtc2l6ZToxMnB4O2ZvbnQtZmFtaWx5OkFyaWFsLEhlbHZldGljYSxzYW5zLXNlcmlmO2RvbWluYW50LWJhc2VsaW5lOmNlbnRyYWwiPjE2MngxODA8L3RleHQ+PC9zdmc+" alt="100%x180" style="height: 180px; width: 100%; display: block;" data-src="holder.js/100%x180">
									</a>
								</div>
							</div>   
						</div>
					</div>
                        
                
                
            </div>
            <div class="modal-footer">
                <button class="btn default" data-dismiss="modal" aria-hidden="true">Kapat</button>
                <button class="btn yellow">Kaydet</button>
            </div>
        </div>
    </div>
</div>