<!-- DOC: Apply "hor-menu-light" class after the "hor-menu" class below to have a horizontal menu with white background -->
<!-- DOC: This is desktop version of the horizontal menu. The mobile version is defined(duplicated) sidebar menu below. So the horizontal menu has 2 seperate versions -->
		
<div class="hor-menu hor-menu-light hidden-sm hidden-xs">
    <ul class="nav navbar-nav">
        <!-- DOC: Remove data-hover="dropdown" and data-close-others="true" attributes below to disable the horizontal opening on mouse hover -->
        <li class="classic-menu-dropdown active">
            <a href="/">
                Anasayfa <?php  if ($this->dispatcher->getControllerName() == 'index') echo '<span class="selected"></span>' ?>
            </a>
        </li>
        <li class="classic-menu-dropdown">
            <a data-hover="dropdown" data-close-others="true" data-toggle="dropdown" href="javascript:;">
                Kategori <i class="fa fa-angle-down"></i><span class="selected"></span>
            </a>
            <ul class="dropdown-menu pull-left">
                <li>
                    <a href="/category/assignUnrelatedCategories">
                        <i class="fa fa-unlink"></i>Kategori Eşleştirme</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="#">Çıkış </a>
        </li>
    </ul>
</div>