<!DOCTYPE html>
<html>
    <head>
        <?php echo $this->tag->getTitle() ?>
        <meta charset="utf-8" lang="tr" />
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <?php echo $this->elements->getMenu() ?>
                </div>
            </div>
        </div>

        <div class="container">
            <?php echo $this->getContent() ?>
            <hr>
            <footer>
                <p>&copy;<a class="brand" href="http://www.popsbuy.com">PopsBuy</a> 2014</p>
            </footer>
        </div>
    </body>
</html>